spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

zuul:
  routes:
    abk-core-service:
      path: /core/**
      serviceId: abk-core-service
  SendErrorFilter:
    error:
      disable: true
  semaphore:
    max-semaphores: 10000

ribbon:
  MaxConnectionsPerHost: 5000
  MaxTotalConnections: 10000
  ReadTimeout: 120000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
        timeout:
          enabled: false

fallback.isolation.semaphore.maxConcurrentRequests: 1000