spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
     
zuul:
  routes:
    abk-core-service:
      path: /core/**
      serviceId: abk-core-service
  SendErrorFilter:
    error:
      disable: true
  semaphore:
    max-semaphores: 2000
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 100

ribbon:
  MaxConnectionsPerHost: 2000
  MaxTotalConnections: 2000
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
