server:
  port: 8076
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 1000


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

zuul:
  routes:
    abk-core-service:
      path: /core/**
      serviceId: abk-core-service
  SendErrorFilter:
    error:
      disable: true
  semaphore:
    max-semaphores: 2000
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 100

ribbon:
  MaxConnectionsPerHost: 2000
  MaxTotalConnections: 2000
  ReadTimeout: 30000
  ConnectTimeout: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
